/**
 * Codealpine
 * The codealpine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ClimbingQuestionnaire from './ClimbingQuestionnaire';
import ClimbingQuestionnaireAnalysis from './ClimbingQuestionnaireAnalysis';

/**
 * The ClimbingQuestionnaireUser model module.
 * @module model/ClimbingQuestionnaireUser
 * @version 1.0
 */
class ClimbingQuestionnaireUser {
    /**
     * Constructs a new <code>ClimbingQuestionnaireUser</code>.
     * @alias module:model/ClimbingQuestionnaireUser
     * @param id {Number} 
     * @param userId {String} 
     * @param result {Number} 
     * @param answers {Object} 
     * @param questionnaires {Array.<module:model/ClimbingQuestionnaire>} 
     * @param analysis {module:model/ClimbingQuestionnaireAnalysis} 
     * @param createdAt {Date} 
     */
    constructor(id, userId, result, answers, questionnaires, analysis, createdAt) { 
        
        ClimbingQuestionnaireUser.initialize(this, id, userId, result, answers, questionnaires, analysis, createdAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, userId, result, answers, questionnaires, analysis, createdAt) { 
        obj['id'] = id;
        obj['userId'] = userId;
        obj['result'] = result;
        obj['answers'] = answers;
        obj['questionnaires'] = questionnaires;
        obj['analysis'] = analysis;
        obj['createdAt'] = createdAt;
    }

    /**
     * Constructs a <code>ClimbingQuestionnaireUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClimbingQuestionnaireUser} obj Optional instance to populate.
     * @return {module:model/ClimbingQuestionnaireUser} The populated <code>ClimbingQuestionnaireUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClimbingQuestionnaireUser();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], 'Number');
            }
            if (data.hasOwnProperty('answers')) {
                obj['answers'] = ApiClient.convertToType(data['answers'], Object);
            }
            if (data.hasOwnProperty('questionnaires')) {
                obj['questionnaires'] = ApiClient.convertToType(data['questionnaires'], [ClimbingQuestionnaire]);
            }
            if (data.hasOwnProperty('analysis')) {
                obj['analysis'] = ClimbingQuestionnaireAnalysis.constructFromObject(data['analysis']);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
ClimbingQuestionnaireUser.prototype['id'] = undefined;

/**
 * @member {String} userId
 */
ClimbingQuestionnaireUser.prototype['userId'] = undefined;

/**
 * @member {Number} result
 */
ClimbingQuestionnaireUser.prototype['result'] = undefined;

/**
 * @member {Object} answers
 */
ClimbingQuestionnaireUser.prototype['answers'] = undefined;

/**
 * @member {Array.<module:model/ClimbingQuestionnaire>} questionnaires
 */
ClimbingQuestionnaireUser.prototype['questionnaires'] = undefined;

/**
 * @member {module:model/ClimbingQuestionnaireAnalysis} analysis
 */
ClimbingQuestionnaireUser.prototype['analysis'] = undefined;

/**
 * @member {Date} createdAt
 */
ClimbingQuestionnaireUser.prototype['createdAt'] = undefined;






export default ClimbingQuestionnaireUser;

