/*
 * Codealpine
 * The codealpine API description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ClimbingQuestionnaire} from './ClimbingQuestionnaire';
import {ClimbingQuestionnaireAnalysis} from './ClimbingQuestionnaireAnalysis';
import {UserResponses} from './UserResponses';

/**
 * The ClimbingQuestionnaireUser model module.
 * @module model/ClimbingQuestionnaireUser
 * @version 1.0
 */
export class ClimbingQuestionnaireUser {
  /**
   * Constructs a new <code>ClimbingQuestionnaireUser</code>.
   * @alias module:model/ClimbingQuestionnaireUser
   * @class
   * @param id {Number} 
   * @param userId {String} 
   * @param result {Number} 
   * @param analysis {module:model/ClimbingQuestionnaireAnalysis} 
   * @param answers {module:model/UserResponses} 
   * @param questionnaires {module:model/ClimbingQuestionnaire} 
   * @param createdAt {Date} 
   */
  constructor(id, userId, result, analysis, answers, questionnaires, createdAt) {
    this.id = id;
    this.userId = userId;
    this.result = result;
    this.analysis = analysis;
    this.answers = answers;
    this.questionnaires = questionnaires;
    this.createdAt = createdAt;
  }

  /**
   * Constructs a <code>ClimbingQuestionnaireUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClimbingQuestionnaireUser} obj Optional instance to populate.
   * @return {module:model/ClimbingQuestionnaireUser} The populated <code>ClimbingQuestionnaireUser</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClimbingQuestionnaireUser();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('result'))
        obj.result = ApiClient.convertToType(data['result'], 'Number');
      if (data.hasOwnProperty('analysis'))
        obj.analysis = ClimbingQuestionnaireAnalysis.constructFromObject(data['analysis']);
      if (data.hasOwnProperty('answers'))
        obj.answers = UserResponses.constructFromObject(data['answers']);
      if (data.hasOwnProperty('questionnaires'))
        obj.questionnaires = ClimbingQuestionnaire.constructFromObject(data['questionnaires']);
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ClimbingQuestionnaireUser.prototype.id = undefined;

/**
 * @member {String} userId
 */
ClimbingQuestionnaireUser.prototype.userId = undefined;

/**
 * @member {Number} result
 */
ClimbingQuestionnaireUser.prototype.result = undefined;

/**
 * @member {module:model/ClimbingQuestionnaireAnalysis} analysis
 */
ClimbingQuestionnaireUser.prototype.analysis = undefined;

/**
 * @member {module:model/UserResponses} answers
 */
ClimbingQuestionnaireUser.prototype.answers = undefined;

/**
 * @member {module:model/ClimbingQuestionnaire} questionnaires
 */
ClimbingQuestionnaireUser.prototype.questionnaires = undefined;

/**
 * @member {Date} createdAt
 */
ClimbingQuestionnaireUser.prototype.createdAt = undefined;

