/*
 * Codealpine
 * The codealpine API description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ClimbingQuestion} from './ClimbingQuestion';
import {ClimbingQuestionnaireAnalysis} from './ClimbingQuestionnaireAnalysis';
import {ClimbingQuestionnaireUser} from './ClimbingQuestionnaireUser';

/**
 * The ClimbingQuestionnaire model module.
 * @module model/ClimbingQuestionnaire
 * @version 1.0
 */
export class ClimbingQuestionnaire {
  /**
   * Constructs a new <code>ClimbingQuestionnaire</code>.
   * @alias module:model/ClimbingQuestionnaire
   * @class
   * @param id {Number} 
   * @param slug {String} 
   * @param title {String} 
   * @param description {String} 
   * @param accessRequired {String} 
   * @param climbingQuestion {module:model/ClimbingQuestion} 
   * @param analysis {module:model/ClimbingQuestionnaireAnalysis} 
   * @param userResponses {module:model/ClimbingQuestionnaireUser} 
   */
  constructor(id, slug, title, description, accessRequired, climbingQuestion, analysis, userResponses) {
    this.id = id;
    this.slug = slug;
    this.title = title;
    this.description = description;
    this.accessRequired = accessRequired;
    this.climbingQuestion = climbingQuestion;
    this.analysis = analysis;
    this.userResponses = userResponses;
  }

  /**
   * Constructs a <code>ClimbingQuestionnaire</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClimbingQuestionnaire} obj Optional instance to populate.
   * @return {module:model/ClimbingQuestionnaire} The populated <code>ClimbingQuestionnaire</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClimbingQuestionnaire();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('accessRequired'))
        obj.accessRequired = ApiClient.convertToType(data['accessRequired'], 'String');
      if (data.hasOwnProperty('climbingQuestion'))
        obj.climbingQuestion = ClimbingQuestion.constructFromObject(data['climbingQuestion']);
      if (data.hasOwnProperty('analysis'))
        obj.analysis = ClimbingQuestionnaireAnalysis.constructFromObject(data['analysis']);
      if (data.hasOwnProperty('userResponses'))
        obj.userResponses = ClimbingQuestionnaireUser.constructFromObject(data['userResponses']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ClimbingQuestionnaire.prototype.id = undefined;

/**
 * @member {String} slug
 */
ClimbingQuestionnaire.prototype.slug = undefined;

/**
 * @member {String} title
 */
ClimbingQuestionnaire.prototype.title = undefined;

/**
 * @member {String} description
 */
ClimbingQuestionnaire.prototype.description = undefined;

/**
 * @member {String} accessRequired
 */
ClimbingQuestionnaire.prototype.accessRequired = undefined;

/**
 * @member {module:model/ClimbingQuestion} climbingQuestion
 */
ClimbingQuestionnaire.prototype.climbingQuestion = undefined;

/**
 * @member {module:model/ClimbingQuestionnaireAnalysis} analysis
 */
ClimbingQuestionnaire.prototype.analysis = undefined;

/**
 * @member {module:model/ClimbingQuestionnaireUser} userResponses
 */
ClimbingQuestionnaire.prototype.userResponses = undefined;

