/*
 * Codealpine
 * The codealpine API description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateNavlinkDto model module.
 * @module model/CreateNavlinkDto
 * @version 1.0
 */
export class CreateNavlinkDto {
  /**
   * Constructs a new <code>CreateNavlinkDto</code>.
   * @alias module:model/CreateNavlinkDto
   * @class
   * @param name {String} 
   * @param href {String} 
   * @param isActive {Boolean} 
   */
  constructor(name, href, isActive) {
    this.name = name;
    this.href = href;
    this.isActive = isActive;
  }

  /**
   * Constructs a <code>CreateNavlinkDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateNavlinkDto} obj Optional instance to populate.
   * @return {module:model/CreateNavlinkDto} The populated <code>CreateNavlinkDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateNavlinkDto();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('href'))
        obj.href = ApiClient.convertToType(data['href'], 'String');
      if (data.hasOwnProperty('isActive'))
        obj.isActive = ApiClient.convertToType(data['isActive'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
CreateNavlinkDto.prototype.name = undefined;

/**
 * @member {String} href
 */
CreateNavlinkDto.prototype.href = undefined;

/**
 * @member {Boolean} isActive
 */
CreateNavlinkDto.prototype.isActive = undefined;

