/**
 * Codealpine
 * The codealpine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateNotificationDto model module.
 * @module model/CreateNotificationDto
 * @version 1.0
 */
class CreateNotificationDto {
    /**
     * Constructs a new <code>CreateNotificationDto</code>.
     * @alias module:model/CreateNotificationDto
     * @param id {Number} 
     * @param title {String} 
     * @param message {String} 
     * @param level {Number} 
     * @param created {Number} 
     */
    constructor(id, title, message, level, created) { 
        
        CreateNotificationDto.initialize(this, id, title, message, level, created);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, title, message, level, created) { 
        obj['id'] = id;
        obj['title'] = title;
        obj['message'] = message;
        obj['level'] = level;
        obj['created'] = created;
    }

    /**
     * Constructs a <code>CreateNotificationDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateNotificationDto} obj Optional instance to populate.
     * @return {module:model/CreateNotificationDto} The populated <code>CreateNotificationDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateNotificationDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'Number');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
CreateNotificationDto.prototype['id'] = undefined;

/**
 * @member {String} title
 */
CreateNotificationDto.prototype['title'] = undefined;

/**
 * @member {String} message
 */
CreateNotificationDto.prototype['message'] = undefined;

/**
 * @member {Number} level
 */
CreateNotificationDto.prototype['level'] = undefined;

/**
 * @member {Number} created
 */
CreateNotificationDto.prototype['created'] = undefined;






export default CreateNotificationDto;

