/*
 * Codealpine
 * The codealpine API description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Notification model module.
 * @module model/Notification
 * @version 1.0
 */
export class Notification {
  /**
   * Constructs a new <code>Notification</code>.
   * @alias module:model/Notification
   * @class
   * @param id {Number} 
   * @param title {String} 
   * @param message {String} 
   * @param level {Number} 
   */
  constructor(id, title, message, level) {
    this.id = id;
    this.title = title;
    this.message = message;
    this.level = level;
  }

  /**
   * Constructs a <code>Notification</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Notification} obj Optional instance to populate.
   * @return {module:model/Notification} The populated <code>Notification</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Notification();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('level'))
        obj.level = ApiClient.convertToType(data['level'], 'Number');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Notification.prototype.id = undefined;

/**
 * @member {String} title
 */
Notification.prototype.title = undefined;

/**
 * @member {String} message
 */
Notification.prototype.message = undefined;

/**
 * @member {Number} level
 */
Notification.prototype.level = undefined;

/**
 * @member {Number} created
 */
Notification.prototype.created = undefined;

