/*
 * Codealpine
 * The codealpine API description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UpdateNotificationDto model module.
 * @module model/UpdateNotificationDto
 * @version 1.0
 */
export class UpdateNotificationDto {
  /**
   * Constructs a new <code>UpdateNotificationDto</code>.
   * @alias module:model/UpdateNotificationDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UpdateNotificationDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateNotificationDto} obj Optional instance to populate.
   * @return {module:model/UpdateNotificationDto} The populated <code>UpdateNotificationDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateNotificationDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('level'))
        obj.level = ApiClient.convertToType(data['level'], 'Number');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
UpdateNotificationDto.prototype.id = undefined;

/**
 * @member {String} title
 */
UpdateNotificationDto.prototype.title = undefined;

/**
 * @member {String} message
 */
UpdateNotificationDto.prototype.message = undefined;

/**
 * @member {Number} level
 */
UpdateNotificationDto.prototype.level = undefined;

/**
 * @member {Number} created
 */
UpdateNotificationDto.prototype.created = undefined;

