/**
 * Codealpine
 * The codealpine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateNavlinkDto model module.
 * @module model/UpdateNavlinkDto
 * @version 1.0
 */
class UpdateNavlinkDto {
    /**
     * Constructs a new <code>UpdateNavlinkDto</code>.
     * @alias module:model/UpdateNavlinkDto
     * @param name {String} 
     * @param href {String} 
     * @param isActive {Boolean} 
     */
    constructor(name, href, isActive) { 
        
        UpdateNavlinkDto.initialize(this, name, href, isActive);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, href, isActive) { 
        obj['name'] = name;
        obj['href'] = href;
        obj['isActive'] = isActive;
    }

    /**
     * Constructs a <code>UpdateNavlinkDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateNavlinkDto} obj Optional instance to populate.
     * @return {module:model/UpdateNavlinkDto} The populated <code>UpdateNavlinkDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateNavlinkDto();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('href')) {
                obj['href'] = ApiClient.convertToType(data['href'], 'String');
            }
            if (data.hasOwnProperty('isActive')) {
                obj['isActive'] = ApiClient.convertToType(data['isActive'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
UpdateNavlinkDto.prototype['name'] = undefined;

/**
 * @member {String} href
 */
UpdateNavlinkDto.prototype['href'] = undefined;

/**
 * @member {Boolean} isActive
 */
UpdateNavlinkDto.prototype['isActive'] = undefined;






export default UpdateNavlinkDto;

