/*
 * Codealpine
 * The codealpine API description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UpdateUserDto model module.
 * @module model/UpdateUserDto
 * @version 1.0
 */
export class UpdateUserDto {
  /**
   * Constructs a new <code>UpdateUserDto</code>.
   * @alias module:model/UpdateUserDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UpdateUserDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateUserDto} obj Optional instance to populate.
   * @return {module:model/UpdateUserDto} The populated <code>UpdateUserDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateUserDto();
    }
    return obj;
  }
}
