/*
 * Codealpine
 * The codealpine API description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Codealpine);
  }
}(this, function(expect, Codealpine) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ClimbingQuestionnaireAnalysis', function() {
      beforeEach(function() {
        instance = new Codealpine.ClimbingQuestionnaireAnalysis();
      });

      it('should create an instance of ClimbingQuestionnaireAnalysis', function() {
        // TODO: update the code to test ClimbingQuestionnaireAnalysis
        expect(instance).to.be.a(Codealpine.ClimbingQuestionnaireAnalysis);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property message (base name: "message")', function() {
        // TODO: update the code to test the property message
        expect(instance).to.have.property('message');
        // expect(instance.message).to.be(expectedValueLiteral);
      });

      it('should have the property minValue (base name: "minValue")', function() {
        // TODO: update the code to test the property minValue
        expect(instance).to.have.property('minValue');
        // expect(instance.minValue).to.be(expectedValueLiteral);
      });

      it('should have the property maxValue (base name: "maxValue")', function() {
        // TODO: update the code to test the property maxValue
        expect(instance).to.have.property('maxValue');
        // expect(instance.maxValue).to.be(expectedValueLiteral);
      });

      it('should have the property questionnaire (base name: "questionnaire")', function() {
        // TODO: update the code to test the property questionnaire
        expect(instance).to.have.property('questionnaire');
        // expect(instance.questionnaire).to.be(expectedValueLiteral);
      });

      it('should have the property userResponse (base name: "userResponse")', function() {
        // TODO: update the code to test the property userResponse
        expect(instance).to.have.property('userResponse');
        // expect(instance.userResponse).to.be(expectedValueLiteral);
      });

    });
  });

}));
