/**
 * Codealpine
 * The codealpine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ClimbingProvidedAnswers from './model/ClimbingProvidedAnswers';
import ClimbingQuestion from './model/ClimbingQuestion';
import ClimbingQuestionnaire from './model/ClimbingQuestionnaire';
import ClimbingQuestionnaireAnalysis from './model/ClimbingQuestionnaireAnalysis';
import ClimbingQuestionnaireUser from './model/ClimbingQuestionnaireUser';
import CreateNavlinkDto from './model/CreateNavlinkDto';
import CreateNotificationDto from './model/CreateNotificationDto';
import Notification from './model/Notification';
import UpdateNavlinkDto from './model/UpdateNavlinkDto';
import UpdateNotificationDto from './model/UpdateNotificationDto';
import ClimbingQuestionnaireApi from './api/ClimbingQuestionnaireApi';
import ClimbingStatsApi from './api/ClimbingStatsApi';
import DefaultApi from './api/DefaultApi';
import NavigationLinksApi from './api/NavigationLinksApi';
import NotificationsApi from './api/NotificationsApi';
import UsersApi from './api/UsersApi';


/**
* The_codealpine_API_description.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Codealpine = require('index'); // See note below*.
* var xxxSvc = new Codealpine.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Codealpine.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Codealpine.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Codealpine.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ClimbingProvidedAnswers model constructor.
     * @property {module:model/ClimbingProvidedAnswers}
     */
    ClimbingProvidedAnswers,

    /**
     * The ClimbingQuestion model constructor.
     * @property {module:model/ClimbingQuestion}
     */
    ClimbingQuestion,

    /**
     * The ClimbingQuestionnaire model constructor.
     * @property {module:model/ClimbingQuestionnaire}
     */
    ClimbingQuestionnaire,

    /**
     * The ClimbingQuestionnaireAnalysis model constructor.
     * @property {module:model/ClimbingQuestionnaireAnalysis}
     */
    ClimbingQuestionnaireAnalysis,

    /**
     * The ClimbingQuestionnaireUser model constructor.
     * @property {module:model/ClimbingQuestionnaireUser}
     */
    ClimbingQuestionnaireUser,

    /**
     * The CreateNavlinkDto model constructor.
     * @property {module:model/CreateNavlinkDto}
     */
    CreateNavlinkDto,

    /**
     * The CreateNotificationDto model constructor.
     * @property {module:model/CreateNotificationDto}
     */
    CreateNotificationDto,

    /**
     * The Notification model constructor.
     * @property {module:model/Notification}
     */
    Notification,

    /**
     * The UpdateNavlinkDto model constructor.
     * @property {module:model/UpdateNavlinkDto}
     */
    UpdateNavlinkDto,

    /**
     * The UpdateNotificationDto model constructor.
     * @property {module:model/UpdateNotificationDto}
     */
    UpdateNotificationDto,

    /**
    * The ClimbingQuestionnaireApi service constructor.
    * @property {module:api/ClimbingQuestionnaireApi}
    */
    ClimbingQuestionnaireApi,

    /**
    * The ClimbingStatsApi service constructor.
    * @property {module:api/ClimbingStatsApi}
    */
    ClimbingStatsApi,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The NavigationLinksApi service constructor.
    * @property {module:api/NavigationLinksApi}
    */
    NavigationLinksApi,

    /**
    * The NotificationsApi service constructor.
    * @property {module:api/NotificationsApi}
    */
    NotificationsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
