/*
 * Codealpine
 * The codealpine API description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Codealpine);
  }
}(this, function(expect, Codealpine) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Codealpine.ClimbingQuestionnaireApi();
  });

  describe('(package)', function() {
    describe('ClimbingQuestionnaireApi', function() {
      describe('climbingQuestionnaireControllerFindAll', function() {
        it('should call climbingQuestionnaireControllerFindAll successfully', function(done) {
          // TODO: uncomment, update parameter values for climbingQuestionnaireControllerFindAll call and complete the assertions
          /*

          instance.climbingQuestionnaireControllerFindAll(withQuestions, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Codealpine.ClimbingQuestionnaire);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('climbingQuestionnaireControllerFindForUser', function() {
        it('should call climbingQuestionnaireControllerFindForUser successfully', function(done) {
          // TODO: uncomment, update parameter values for climbingQuestionnaireControllerFindForUser call and complete the assertions
          /*

          instance.climbingQuestionnaireControllerFindForUser(authorization, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Codealpine.ClimbingQuestionnaire);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('climbingQuestionnaireControllerFindOne', function() {
        it('should call climbingQuestionnaireControllerFindOne successfully', function(done) {
          // TODO: uncomment, update parameter values for climbingQuestionnaireControllerFindOne call and complete the assertions
          /*

          instance.climbingQuestionnaireControllerFindOne(id, withQuestions, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Codealpine.ClimbingQuestionnaire);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('climbingQuestionnaireControllerGetAnalysisMessage', function() {
        it('should call climbingQuestionnaireControllerGetAnalysisMessage successfully', function(done) {
          // TODO: uncomment, update parameter values for climbingQuestionnaireControllerGetAnalysisMessage call
          /*

          instance.climbingQuestionnaireControllerGetAnalysisMessage(questionnaire, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('climbingQuestionnaireControllerSaveUserQuestionnaire', function() {
        it('should call climbingQuestionnaireControllerSaveUserQuestionnaire successfully', function(done) {
          // TODO: uncomment, update parameter values for climbingQuestionnaireControllerSaveUserQuestionnaire call
          /*

          instance.climbingQuestionnaireControllerSaveUserQuestionnaire(authorization, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
