/**
 * Codealpine
 * The codealpine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Codealpine);
  }
}(this, function(expect, Codealpine) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Codealpine.ClimbingQuestionnaireApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ClimbingQuestionnaireApi', function() {
    describe('climbingQuestionnaireControllerFindAll', function() {
      it('should call climbingQuestionnaireControllerFindAll successfully', function(done) {
        //uncomment below and update the code to test climbingQuestionnaireControllerFindAll
        //instance.climbingQuestionnaireControllerFindAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('climbingQuestionnaireControllerFindForUser', function() {
      it('should call climbingQuestionnaireControllerFindForUser successfully', function(done) {
        //uncomment below and update the code to test climbingQuestionnaireControllerFindForUser
        //instance.climbingQuestionnaireControllerFindForUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('climbingQuestionnaireControllerFindOne', function() {
      it('should call climbingQuestionnaireControllerFindOne successfully', function(done) {
        //uncomment below and update the code to test climbingQuestionnaireControllerFindOne
        //instance.climbingQuestionnaireControllerFindOne(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('climbingQuestionnaireControllerGetAnalysisMessage', function() {
      it('should call climbingQuestionnaireControllerGetAnalysisMessage successfully', function(done) {
        //uncomment below and update the code to test climbingQuestionnaireControllerGetAnalysisMessage
        //instance.climbingQuestionnaireControllerGetAnalysisMessage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('climbingQuestionnaireControllerSaveUserQuestionnaire', function() {
      it('should call climbingQuestionnaireControllerSaveUserQuestionnaire successfully', function(done) {
        //uncomment below and update the code to test climbingQuestionnaireControllerSaveUserQuestionnaire
        //instance.climbingQuestionnaireControllerSaveUserQuestionnaire(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
