/**
 * codealpine api
 * The codealpine API description
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClimbingProvidedAnswers } from './ClimbingProvidedAnswers';
import { ClimbingQuestionnaire } from './ClimbingQuestionnaire';
import { HttpFile } from '../http/http';

export class ClimbingQuestion {
    'id': number;
    'slug': string;
    'question': string;
    'questionnaire': ClimbingQuestionnaire;
    'answers': ClimbingProvidedAnswers;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "question",
            "baseName": "question",
            "type": "string",
            "format": ""
        },
        {
            "name": "questionnaire",
            "baseName": "questionnaire",
            "type": "ClimbingQuestionnaire",
            "format": ""
        },
        {
            "name": "answers",
            "baseName": "answers",
            "type": "ClimbingProvidedAnswers",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClimbingQuestion.attributeTypeMap;
    }
    
    public constructor() {
    }
}

