/**
 * codealpine api
 * The codealpine API description
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClimbingQuestion } from './ClimbingQuestion';
import { HttpFile } from '../http/http';

export class ClimbingProvidedAnswers {
    'id': number;
    'value': number;
    'answer': string;
    'question': ClimbingQuestion;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number",
            "format": ""
        },
        {
            "name": "answer",
            "baseName": "answer",
            "type": "string",
            "format": ""
        },
        {
            "name": "question",
            "baseName": "question",
            "type": "ClimbingQuestion",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClimbingProvidedAnswers.attributeTypeMap;
    }
    
    public constructor() {
    }
}

