/**
 * codealpine api
 * The codealpine API description
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClimbingQuestionnaire } from './ClimbingQuestionnaire';
import { ClimbingQuestionnaireAnalysis } from './ClimbingQuestionnaireAnalysis';
import { HttpFile } from '../http/http';

export class ClimbingQuestionnaireUser {
    'id': number;
    'userId': string;
    'result': number;
    'analysis': ClimbingQuestionnaireAnalysis;
    'answers': any;
    'questionnaires': ClimbingQuestionnaire;
    'createdAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": ""
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "number",
            "format": ""
        },
        {
            "name": "analysis",
            "baseName": "analysis",
            "type": "ClimbingQuestionnaireAnalysis",
            "format": ""
        },
        {
            "name": "answers",
            "baseName": "answers",
            "type": "any",
            "format": ""
        },
        {
            "name": "questionnaires",
            "baseName": "questionnaires",
            "type": "ClimbingQuestionnaire",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return ClimbingQuestionnaireUser.attributeTypeMap;
    }
    
    public constructor() {
    }
}

