/**
 * codealpine api
 * The codealpine API description
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClimbingQuestionnaire } from './ClimbingQuestionnaire';
import { ClimbingQuestionnaireUser } from './ClimbingQuestionnaireUser';
import { HttpFile } from '../http/http';

export class ClimbingQuestionnaireAnalysis {
    'id': number;
    'message': string;
    'minValue': number;
    'maxValue': number;
    'questionnaire': ClimbingQuestionnaire;
    'userResponse': ClimbingQuestionnaireUser;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "minValue",
            "baseName": "minValue",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxValue",
            "baseName": "maxValue",
            "type": "number",
            "format": ""
        },
        {
            "name": "questionnaire",
            "baseName": "questionnaire",
            "type": "ClimbingQuestionnaire",
            "format": ""
        },
        {
            "name": "userResponse",
            "baseName": "userResponse",
            "type": "ClimbingQuestionnaireUser",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClimbingQuestionnaireAnalysis.attributeTypeMap;
    }
    
    public constructor() {
    }
}

